version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: WebServer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      GRPC_URL: http://aiserver:5002
    image: us.gcr.io/face-demo-motus/face-demo/app
    ports:
      - 80:5001

  aiserver:
    build:
      context: .
      dockerfile: server/Dockerfile
    image: us.gcr.io/face-demo-motus/face-demo/aiserver
    ports:
      - 5002:5002
    volumes:
      - weights:/root/.keras

volumes:
  weights:
