# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face-identifier.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face-identifier.proto',
  package='FaceIdentifier',
  syntax='proto3',
  serialized_options=b'\252\002\025FaceIdentifierService',
  serialized_pb=b'\n\x15\x66\x61\x63\x65-identifier.proto\x12\x0e\x46\x61\x63\x65Identifier\"#\n\x0fIdentifyRequest\x12\x10\n\x08\x66ilepath\x18\x01 \x01(\t\"%\n\x14IdentifyImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\xc0\x03\n\rIdentifyReply\x12=\n\x07results\x18\x01 \x03(\x0b\x32,.FaceIdentifier.IdentifyReply.IdentifyResult\x1a\xef\x02\n\x0eIdentifyResult\x12J\n\x07nearest\x18\x01 \x01(\x0b\x32\x39.FaceIdentifier.IdentifyReply.IdentifyResult.IdentifyItem\x12K\n\x08\x66urthest\x18\x02 \x01(\x0b\x32\x39.FaceIdentifier.IdentifyReply.IdentifyResult.IdentifyItem\x12M\n\x0b\x62oundingBox\x18\x03 \x01(\x0b\x32\x38.FaceIdentifier.IdentifyReply.IdentifyResult.BoundingBox\x1a.\n\x0cIdentifyItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x1a\x45\n\x0b\x42oundingBox\x12\x0c\n\x04minX\x18\x01 \x01(\x01\x12\x0c\n\x04minY\x18\x02 \x01(\x01\x12\x0c\n\x04maxX\x18\x03 \x01(\x01\x12\x0c\n\x04maxY\x18\x04 \x01(\x01\x32\xb4\x01\n\x0e\x46\x61\x63\x65Identifier\x12J\n\x08Identify\x12\x1f.FaceIdentifier.IdentifyRequest\x1a\x1d.FaceIdentifier.IdentifyReply\x12V\n\rIdentifyImage\x12$.FaceIdentifier.IdentifyImageRequest\x1a\x1d.FaceIdentifier.IdentifyReply(\x01\x42\x18\xaa\x02\x15\x46\x61\x63\x65IdentifierServiceb\x06proto3'
)




_IDENTIFYREQUEST = _descriptor.Descriptor(
  name='IdentifyRequest',
  full_name='FaceIdentifier.IdentifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filepath', full_name='FaceIdentifier.IdentifyRequest.filepath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=76,
)


_IDENTIFYIMAGEREQUEST = _descriptor.Descriptor(
  name='IdentifyImageRequest',
  full_name='FaceIdentifier.IdentifyImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='FaceIdentifier.IdentifyImageRequest.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=115,
)


_IDENTIFYREPLY_IDENTIFYRESULT_IDENTIFYITEM = _descriptor.Descriptor(
  name='IdentifyItem',
  full_name='FaceIdentifier.IdentifyReply.IdentifyResult.IdentifyItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.IdentifyItem.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distance', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.IdentifyItem.distance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=495,
)

_IDENTIFYREPLY_IDENTIFYRESULT_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='FaceIdentifier.IdentifyReply.IdentifyResult.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='minX', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.BoundingBox.minX', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='minY', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.BoundingBox.minY', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxX', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.BoundingBox.maxX', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxY', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.BoundingBox.maxY', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=566,
)

_IDENTIFYREPLY_IDENTIFYRESULT = _descriptor.Descriptor(
  name='IdentifyResult',
  full_name='FaceIdentifier.IdentifyReply.IdentifyResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nearest', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.nearest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='furthest', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.furthest', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boundingBox', full_name='FaceIdentifier.IdentifyReply.IdentifyResult.boundingBox', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_IDENTIFYREPLY_IDENTIFYRESULT_IDENTIFYITEM, _IDENTIFYREPLY_IDENTIFYRESULT_BOUNDINGBOX, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=566,
)

_IDENTIFYREPLY = _descriptor.Descriptor(
  name='IdentifyReply',
  full_name='FaceIdentifier.IdentifyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='results', full_name='FaceIdentifier.IdentifyReply.results', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_IDENTIFYREPLY_IDENTIFYRESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=566,
)

_IDENTIFYREPLY_IDENTIFYRESULT_IDENTIFYITEM.containing_type = _IDENTIFYREPLY_IDENTIFYRESULT
_IDENTIFYREPLY_IDENTIFYRESULT_BOUNDINGBOX.containing_type = _IDENTIFYREPLY_IDENTIFYRESULT
_IDENTIFYREPLY_IDENTIFYRESULT.fields_by_name['nearest'].message_type = _IDENTIFYREPLY_IDENTIFYRESULT_IDENTIFYITEM
_IDENTIFYREPLY_IDENTIFYRESULT.fields_by_name['furthest'].message_type = _IDENTIFYREPLY_IDENTIFYRESULT_IDENTIFYITEM
_IDENTIFYREPLY_IDENTIFYRESULT.fields_by_name['boundingBox'].message_type = _IDENTIFYREPLY_IDENTIFYRESULT_BOUNDINGBOX
_IDENTIFYREPLY_IDENTIFYRESULT.containing_type = _IDENTIFYREPLY
_IDENTIFYREPLY.fields_by_name['results'].message_type = _IDENTIFYREPLY_IDENTIFYRESULT
DESCRIPTOR.message_types_by_name['IdentifyRequest'] = _IDENTIFYREQUEST
DESCRIPTOR.message_types_by_name['IdentifyImageRequest'] = _IDENTIFYIMAGEREQUEST
DESCRIPTOR.message_types_by_name['IdentifyReply'] = _IDENTIFYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IdentifyRequest = _reflection.GeneratedProtocolMessageType('IdentifyRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFYREQUEST,
  '__module__' : 'face_identifier_pb2'
  # @@protoc_insertion_point(class_scope:FaceIdentifier.IdentifyRequest)
  })
_sym_db.RegisterMessage(IdentifyRequest)

IdentifyImageRequest = _reflection.GeneratedProtocolMessageType('IdentifyImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFYIMAGEREQUEST,
  '__module__' : 'face_identifier_pb2'
  # @@protoc_insertion_point(class_scope:FaceIdentifier.IdentifyImageRequest)
  })
_sym_db.RegisterMessage(IdentifyImageRequest)

IdentifyReply = _reflection.GeneratedProtocolMessageType('IdentifyReply', (_message.Message,), {

  'IdentifyResult' : _reflection.GeneratedProtocolMessageType('IdentifyResult', (_message.Message,), {

    'IdentifyItem' : _reflection.GeneratedProtocolMessageType('IdentifyItem', (_message.Message,), {
      'DESCRIPTOR' : _IDENTIFYREPLY_IDENTIFYRESULT_IDENTIFYITEM,
      '__module__' : 'face_identifier_pb2'
      # @@protoc_insertion_point(class_scope:FaceIdentifier.IdentifyReply.IdentifyResult.IdentifyItem)
      })
    ,

    'BoundingBox' : _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), {
      'DESCRIPTOR' : _IDENTIFYREPLY_IDENTIFYRESULT_BOUNDINGBOX,
      '__module__' : 'face_identifier_pb2'
      # @@protoc_insertion_point(class_scope:FaceIdentifier.IdentifyReply.IdentifyResult.BoundingBox)
      })
    ,
    'DESCRIPTOR' : _IDENTIFYREPLY_IDENTIFYRESULT,
    '__module__' : 'face_identifier_pb2'
    # @@protoc_insertion_point(class_scope:FaceIdentifier.IdentifyReply.IdentifyResult)
    })
  ,
  'DESCRIPTOR' : _IDENTIFYREPLY,
  '__module__' : 'face_identifier_pb2'
  # @@protoc_insertion_point(class_scope:FaceIdentifier.IdentifyReply)
  })
_sym_db.RegisterMessage(IdentifyReply)
_sym_db.RegisterMessage(IdentifyReply.IdentifyResult)
_sym_db.RegisterMessage(IdentifyReply.IdentifyResult.IdentifyItem)
_sym_db.RegisterMessage(IdentifyReply.IdentifyResult.BoundingBox)


DESCRIPTOR._options = None

_FACEIDENTIFIER = _descriptor.ServiceDescriptor(
  name='FaceIdentifier',
  full_name='FaceIdentifier.FaceIdentifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=569,
  serialized_end=749,
  methods=[
  _descriptor.MethodDescriptor(
    name='Identify',
    full_name='FaceIdentifier.FaceIdentifier.Identify',
    index=0,
    containing_service=None,
    input_type=_IDENTIFYREQUEST,
    output_type=_IDENTIFYREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IdentifyImage',
    full_name='FaceIdentifier.FaceIdentifier.IdentifyImage',
    index=1,
    containing_service=None,
    input_type=_IDENTIFYIMAGEREQUEST,
    output_type=_IDENTIFYREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACEIDENTIFIER)

DESCRIPTOR.services_by_name['FaceIdentifier'] = _FACEIDENTIFIER

# @@protoc_insertion_point(module_scope)
