// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: face-identifier.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Services {
  public static partial class Identifier
  {
    static readonly string __ServiceName = "FaceIdentifier.Identifier";

    static readonly grpc::Marshaller<global::Services.IdentifyRequest> __Marshaller_FaceIdentifier_IdentifyRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.IdentifyRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Services.IdentifyReply> __Marshaller_FaceIdentifier_IdentifyReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.IdentifyReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Services.IdentifyImageRequest> __Marshaller_FaceIdentifier_IdentifyImageRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.IdentifyImageRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::Services.IdentifyRequest, global::Services.IdentifyReply> __Method_Identify = new grpc::Method<global::Services.IdentifyRequest, global::Services.IdentifyReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Identify",
        __Marshaller_FaceIdentifier_IdentifyRequest,
        __Marshaller_FaceIdentifier_IdentifyReply);

    static readonly grpc::Method<global::Services.IdentifyImageRequest, global::Services.IdentifyReply> __Method_IdentifyImage = new grpc::Method<global::Services.IdentifyImageRequest, global::Services.IdentifyReply>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "IdentifyImage",
        __Marshaller_FaceIdentifier_IdentifyImageRequest,
        __Marshaller_FaceIdentifier_IdentifyReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Services.FaceIdentifierReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for Identifier</summary>
    public partial class IdentifierClient : grpc::ClientBase<IdentifierClient>
    {
      /// <summary>Creates a new client for Identifier</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IdentifierClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Identifier that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IdentifierClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IdentifierClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IdentifierClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Services.IdentifyReply Identify(global::Services.IdentifyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Identify(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Services.IdentifyReply Identify(global::Services.IdentifyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Identify, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Services.IdentifyReply> IdentifyAsync(global::Services.IdentifyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IdentifyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Services.IdentifyReply> IdentifyAsync(global::Services.IdentifyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Identify, null, options, request);
      }
      public virtual grpc::AsyncClientStreamingCall<global::Services.IdentifyImageRequest, global::Services.IdentifyReply> IdentifyImage(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IdentifyImage(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncClientStreamingCall<global::Services.IdentifyImageRequest, global::Services.IdentifyReply> IdentifyImage(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_IdentifyImage, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IdentifierClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IdentifierClient(configuration);
      }
    }

  }
}
#endregion
