// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: face-identifier.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace FaceIdentifierService {

  /// <summary>Holder for reflection information generated from face-identifier.proto</summary>
  public static partial class FaceIdentifierReflection {

    #region Descriptor
    /// <summary>File descriptor for face-identifier.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FaceIdentifierReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVmYWNlLWlkZW50aWZpZXIucHJvdG8SDkZhY2VJZGVudGlmaWVyIiMKD0lk",
            "ZW50aWZ5UmVxdWVzdBIQCghmaWxlcGF0aBgBIAEoCSIlChRJZGVudGlmeUlt",
            "YWdlUmVxdWVzdBINCgVpbWFnZRgBIAEoDCLAAwoNSWRlbnRpZnlSZXBseRI9",
            "CgdyZXN1bHRzGAEgAygLMiwuRmFjZUlkZW50aWZpZXIuSWRlbnRpZnlSZXBs",
            "eS5JZGVudGlmeVJlc3VsdBrvAgoOSWRlbnRpZnlSZXN1bHQSSgoHbmVhcmVz",
            "dBgBIAEoCzI5LkZhY2VJZGVudGlmaWVyLklkZW50aWZ5UmVwbHkuSWRlbnRp",
            "ZnlSZXN1bHQuSWRlbnRpZnlJdGVtEksKCGZ1cnRoZXN0GAIgASgLMjkuRmFj",
            "ZUlkZW50aWZpZXIuSWRlbnRpZnlSZXBseS5JZGVudGlmeVJlc3VsdC5JZGVu",
            "dGlmeUl0ZW0STQoLYm91bmRpbmdCb3gYAyABKAsyOC5GYWNlSWRlbnRpZmll",
            "ci5JZGVudGlmeVJlcGx5LklkZW50aWZ5UmVzdWx0LkJvdW5kaW5nQm94Gi4K",
            "DElkZW50aWZ5SXRlbRIMCgRuYW1lGAEgASgJEhAKCGRpc3RhbmNlGAIgASgB",
            "GkUKC0JvdW5kaW5nQm94EgwKBG1pblgYASABKAESDAoEbWluWRgCIAEoARIM",
            "CgRtYXhYGAMgASgBEgwKBG1heFkYBCABKAEytAEKDkZhY2VJZGVudGlmaWVy",
            "EkoKCElkZW50aWZ5Eh8uRmFjZUlkZW50aWZpZXIuSWRlbnRpZnlSZXF1ZXN0",
            "Gh0uRmFjZUlkZW50aWZpZXIuSWRlbnRpZnlSZXBseRJWCg1JZGVudGlmeUlt",
            "YWdlEiQuRmFjZUlkZW50aWZpZXIuSWRlbnRpZnlJbWFnZVJlcXVlc3QaHS5G",
            "YWNlSWRlbnRpZmllci5JZGVudGlmeVJlcGx5KAFCGKoCFUZhY2VJZGVudGlm",
            "aWVyU2VydmljZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::FaceIdentifierService.IdentifyRequest), global::FaceIdentifierService.IdentifyRequest.Parser, new[]{ "Filepath" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FaceIdentifierService.IdentifyImageRequest), global::FaceIdentifierService.IdentifyImageRequest.Parser, new[]{ "Image" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FaceIdentifierService.IdentifyReply), global::FaceIdentifierService.IdentifyReply.Parser, new[]{ "Results" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult), global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Parser, new[]{ "Nearest", "Furthest", "BoundingBox" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem), global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem.Parser, new[]{ "Name", "Distance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.BoundingBox), global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.BoundingBox.Parser, new[]{ "MinX", "MinY", "MaxX", "MaxY" }, null, null, null, null)})})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The request message containing the user's name.
  /// </summary>
  public sealed partial class IdentifyRequest : pb::IMessage<IdentifyRequest> {
    private static readonly pb::MessageParser<IdentifyRequest> _parser = new pb::MessageParser<IdentifyRequest>(() => new IdentifyRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IdentifyRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FaceIdentifierService.FaceIdentifierReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyRequest(IdentifyRequest other) : this() {
      filepath_ = other.filepath_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyRequest Clone() {
      return new IdentifyRequest(this);
    }

    /// <summary>Field number for the "filepath" field.</summary>
    public const int FilepathFieldNumber = 1;
    private string filepath_ = "";
    /// <summary>
    ///bytes image = 1;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Filepath {
      get { return filepath_; }
      set {
        filepath_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IdentifyRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IdentifyRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Filepath != other.Filepath) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Filepath.Length != 0) hash ^= Filepath.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Filepath.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Filepath);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Filepath.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Filepath);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IdentifyRequest other) {
      if (other == null) {
        return;
      }
      if (other.Filepath.Length != 0) {
        Filepath = other.Filepath;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Filepath = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class IdentifyImageRequest : pb::IMessage<IdentifyImageRequest> {
    private static readonly pb::MessageParser<IdentifyImageRequest> _parser = new pb::MessageParser<IdentifyImageRequest>(() => new IdentifyImageRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IdentifyImageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FaceIdentifierService.FaceIdentifierReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyImageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyImageRequest(IdentifyImageRequest other) : this() {
      image_ = other.image_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyImageRequest Clone() {
      return new IdentifyImageRequest(this);
    }

    /// <summary>Field number for the "image" field.</summary>
    public const int ImageFieldNumber = 1;
    private pb::ByteString image_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Image {
      get { return image_; }
      set {
        image_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IdentifyImageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IdentifyImageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Image != other.Image) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Image.Length != 0) hash ^= Image.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Image.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Image);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Image.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Image);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IdentifyImageRequest other) {
      if (other == null) {
        return;
      }
      if (other.Image.Length != 0) {
        Image = other.Image;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Image = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The response message containing the greetings
  /// </summary>
  public sealed partial class IdentifyReply : pb::IMessage<IdentifyReply> {
    private static readonly pb::MessageParser<IdentifyReply> _parser = new pb::MessageParser<IdentifyReply>(() => new IdentifyReply());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IdentifyReply> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::FaceIdentifierService.FaceIdentifierReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyReply() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyReply(IdentifyReply other) : this() {
      results_ = other.results_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IdentifyReply Clone() {
      return new IdentifyReply(this);
    }

    /// <summary>Field number for the "results" field.</summary>
    public const int ResultsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult> _repeated_results_codec
        = pb::FieldCodec.ForMessage(10, global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Parser);
    private readonly pbc::RepeatedField<global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult> results_ = new pbc::RepeatedField<global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult> Results {
      get { return results_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IdentifyReply);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IdentifyReply other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!results_.Equals(other.results_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= results_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      results_.WriteTo(output, _repeated_results_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += results_.CalculateSize(_repeated_results_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IdentifyReply other) {
      if (other == null) {
        return;
      }
      results_.Add(other.results_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            results_.AddEntriesFrom(input, _repeated_results_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the IdentifyReply message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class IdentifyResult : pb::IMessage<IdentifyResult> {
        private static readonly pb::MessageParser<IdentifyResult> _parser = new pb::MessageParser<IdentifyResult>(() => new IdentifyResult());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<IdentifyResult> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::FaceIdentifierService.IdentifyReply.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public IdentifyResult() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public IdentifyResult(IdentifyResult other) : this() {
          nearest_ = other.nearest_ != null ? other.nearest_.Clone() : null;
          furthest_ = other.furthest_ != null ? other.furthest_.Clone() : null;
          boundingBox_ = other.boundingBox_ != null ? other.boundingBox_.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public IdentifyResult Clone() {
          return new IdentifyResult(this);
        }

        /// <summary>Field number for the "nearest" field.</summary>
        public const int NearestFieldNumber = 1;
        private global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem nearest_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem Nearest {
          get { return nearest_; }
          set {
            nearest_ = value;
          }
        }

        /// <summary>Field number for the "furthest" field.</summary>
        public const int FurthestFieldNumber = 2;
        private global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem furthest_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem Furthest {
          get { return furthest_; }
          set {
            furthest_ = value;
          }
        }

        /// <summary>Field number for the "boundingBox" field.</summary>
        public const int BoundingBoxFieldNumber = 3;
        private global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.BoundingBox boundingBox_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.BoundingBox BoundingBox {
          get { return boundingBox_; }
          set {
            boundingBox_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as IdentifyResult);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(IdentifyResult other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(Nearest, other.Nearest)) return false;
          if (!object.Equals(Furthest, other.Furthest)) return false;
          if (!object.Equals(BoundingBox, other.BoundingBox)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (nearest_ != null) hash ^= Nearest.GetHashCode();
          if (furthest_ != null) hash ^= Furthest.GetHashCode();
          if (boundingBox_ != null) hash ^= BoundingBox.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (nearest_ != null) {
            output.WriteRawTag(10);
            output.WriteMessage(Nearest);
          }
          if (furthest_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Furthest);
          }
          if (boundingBox_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(BoundingBox);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (nearest_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Nearest);
          }
          if (furthest_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Furthest);
          }
          if (boundingBox_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(BoundingBox);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(IdentifyResult other) {
          if (other == null) {
            return;
          }
          if (other.nearest_ != null) {
            if (nearest_ == null) {
              Nearest = new global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem();
            }
            Nearest.MergeFrom(other.Nearest);
          }
          if (other.furthest_ != null) {
            if (furthest_ == null) {
              Furthest = new global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem();
            }
            Furthest.MergeFrom(other.Furthest);
          }
          if (other.boundingBox_ != null) {
            if (boundingBox_ == null) {
              BoundingBox = new global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.BoundingBox();
            }
            BoundingBox.MergeFrom(other.BoundingBox);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                if (nearest_ == null) {
                  Nearest = new global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem();
                }
                input.ReadMessage(Nearest);
                break;
              }
              case 18: {
                if (furthest_ == null) {
                  Furthest = new global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.IdentifyItem();
                }
                input.ReadMessage(Furthest);
                break;
              }
              case 26: {
                if (boundingBox_ == null) {
                  BoundingBox = new global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Types.BoundingBox();
                }
                input.ReadMessage(BoundingBox);
                break;
              }
            }
          }
        }

        #region Nested types
        /// <summary>Container for nested types declared in the IdentifyResult message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static partial class Types {
          public sealed partial class IdentifyItem : pb::IMessage<IdentifyItem> {
            private static readonly pb::MessageParser<IdentifyItem> _parser = new pb::MessageParser<IdentifyItem>(() => new IdentifyItem());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<IdentifyItem> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Descriptor.NestedTypes[0]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public IdentifyItem() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public IdentifyItem(IdentifyItem other) : this() {
              name_ = other.name_;
              distance_ = other.distance_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public IdentifyItem Clone() {
              return new IdentifyItem(this);
            }

            /// <summary>Field number for the "name" field.</summary>
            public const int NameFieldNumber = 1;
            private string name_ = "";
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public string Name {
              get { return name_; }
              set {
                name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
              }
            }

            /// <summary>Field number for the "distance" field.</summary>
            public const int DistanceFieldNumber = 2;
            private double distance_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public double Distance {
              get { return distance_; }
              set {
                distance_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as IdentifyItem);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(IdentifyItem other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (Name != other.Name) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Distance, other.Distance)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (Name.Length != 0) hash ^= Name.GetHashCode();
              if (Distance != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Distance);
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (Name.Length != 0) {
                output.WriteRawTag(10);
                output.WriteString(Name);
              }
              if (Distance != 0D) {
                output.WriteRawTag(17);
                output.WriteDouble(Distance);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (Name.Length != 0) {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
              }
              if (Distance != 0D) {
                size += 1 + 8;
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(IdentifyItem other) {
              if (other == null) {
                return;
              }
              if (other.Name.Length != 0) {
                Name = other.Name;
              }
              if (other.Distance != 0D) {
                Distance = other.Distance;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 10: {
                    Name = input.ReadString();
                    break;
                  }
                  case 17: {
                    Distance = input.ReadDouble();
                    break;
                  }
                }
              }
            }

          }

          public sealed partial class BoundingBox : pb::IMessage<BoundingBox> {
            private static readonly pb::MessageParser<BoundingBox> _parser = new pb::MessageParser<BoundingBox>(() => new BoundingBox());
            private pb::UnknownFieldSet _unknownFields;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pb::MessageParser<BoundingBox> Parser { get { return _parser; } }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public static pbr::MessageDescriptor Descriptor {
              get { return global::FaceIdentifierService.IdentifyReply.Types.IdentifyResult.Descriptor.NestedTypes[1]; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            pbr::MessageDescriptor pb::IMessage.Descriptor {
              get { return Descriptor; }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public BoundingBox() {
              OnConstruction();
            }

            partial void OnConstruction();

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public BoundingBox(BoundingBox other) : this() {
              minX_ = other.minX_;
              minY_ = other.minY_;
              maxX_ = other.maxX_;
              maxY_ = other.maxY_;
              _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public BoundingBox Clone() {
              return new BoundingBox(this);
            }

            /// <summary>Field number for the "minX" field.</summary>
            public const int MinXFieldNumber = 1;
            private double minX_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public double MinX {
              get { return minX_; }
              set {
                minX_ = value;
              }
            }

            /// <summary>Field number for the "minY" field.</summary>
            public const int MinYFieldNumber = 2;
            private double minY_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public double MinY {
              get { return minY_; }
              set {
                minY_ = value;
              }
            }

            /// <summary>Field number for the "maxX" field.</summary>
            public const int MaxXFieldNumber = 3;
            private double maxX_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public double MaxX {
              get { return maxX_; }
              set {
                maxX_ = value;
              }
            }

            /// <summary>Field number for the "maxY" field.</summary>
            public const int MaxYFieldNumber = 4;
            private double maxY_;
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public double MaxY {
              get { return maxY_; }
              set {
                maxY_ = value;
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override bool Equals(object other) {
              return Equals(other as BoundingBox);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public bool Equals(BoundingBox other) {
              if (ReferenceEquals(other, null)) {
                return false;
              }
              if (ReferenceEquals(other, this)) {
                return true;
              }
              if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MinX, other.MinX)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MinY, other.MinY)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MaxX, other.MaxX)) return false;
              if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MaxY, other.MaxY)) return false;
              return Equals(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override int GetHashCode() {
              int hash = 1;
              if (MinX != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MinX);
              if (MinY != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MinY);
              if (MaxX != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MaxX);
              if (MaxY != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MaxY);
              if (_unknownFields != null) {
                hash ^= _unknownFields.GetHashCode();
              }
              return hash;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public override string ToString() {
              return pb::JsonFormatter.ToDiagnosticString(this);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void WriteTo(pb::CodedOutputStream output) {
              if (MinX != 0D) {
                output.WriteRawTag(9);
                output.WriteDouble(MinX);
              }
              if (MinY != 0D) {
                output.WriteRawTag(17);
                output.WriteDouble(MinY);
              }
              if (MaxX != 0D) {
                output.WriteRawTag(25);
                output.WriteDouble(MaxX);
              }
              if (MaxY != 0D) {
                output.WriteRawTag(33);
                output.WriteDouble(MaxY);
              }
              if (_unknownFields != null) {
                _unknownFields.WriteTo(output);
              }
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public int CalculateSize() {
              int size = 0;
              if (MinX != 0D) {
                size += 1 + 8;
              }
              if (MinY != 0D) {
                size += 1 + 8;
              }
              if (MaxX != 0D) {
                size += 1 + 8;
              }
              if (MaxY != 0D) {
                size += 1 + 8;
              }
              if (_unknownFields != null) {
                size += _unknownFields.CalculateSize();
              }
              return size;
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(BoundingBox other) {
              if (other == null) {
                return;
              }
              if (other.MinX != 0D) {
                MinX = other.MinX;
              }
              if (other.MinY != 0D) {
                MinY = other.MinY;
              }
              if (other.MaxX != 0D) {
                MaxX = other.MaxX;
              }
              if (other.MaxY != 0D) {
                MaxY = other.MaxY;
              }
              _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
            }

            [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
            public void MergeFrom(pb::CodedInputStream input) {
              uint tag;
              while ((tag = input.ReadTag()) != 0) {
                switch(tag) {
                  default:
                    _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                    break;
                  case 9: {
                    MinX = input.ReadDouble();
                    break;
                  }
                  case 17: {
                    MinY = input.ReadDouble();
                    break;
                  }
                  case 25: {
                    MaxX = input.ReadDouble();
                    break;
                  }
                  case 33: {
                    MaxY = input.ReadDouble();
                    break;
                  }
                }
              }
            }

          }

        }
        #endregion

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
